## http://www.3dmenagerie.com/goodies/tut/gsr.htm
## GetStringRes Values (English Version)
## 1024
stringResourceList = {}

sparse_vars = [ (1,"Body"),
(2,"Head"),
(3,"Neck"),
(4,"Chest"),
(5,"Abdomen"),
(6,"Hip"),
(7,"Left Thigh"),
(8,"Left Shin"),
(9,"Left Foot"),
(10,"Right Thigh"),
(11,"Right Shin"),
(12,"Right Foot"),
(13,"Left Shoulder"),
(14,"Left Forearm"),
(15,"Left Hand"),
(16,"Right Shoulder"),
(17,"Right Forearm"),
(18,"Right Hand"),
(19,"Left Collar"),
(20,"Right Collar"),
(21,"Jaw"),
(22,"Left Pinky 1"),
(23,"Left Pinky 2"),
(24,"Left Pinky 3"),
(25,"Right Pinky 1"),
(26,"Right Pinky 2"),
(27,"Right Pinky 3"),
(28,"Left Ring 1"),
(29,"Left Ring 2"),
(30,"Left Ring 3"),
(31,"Right Ring 1"),
(32,"Right Ring 2"),
(33,"Right Ring 3"),
(34,"Left Mid 1"),
(35,"Left Mid 2"),
(36,"Left Mid 3"),
(37,"Right Mid 1"),
(38,"Right Mid 2"),
(39,"Right Mid 3"),
(40,"Left Index 1"),
(41,"Left Index 2"),
(42,"Left Index 3"),
(43,"Right Index 1"),
(44,"Right Index 2"),
(45,"Right Index 3"),
(46,"Left Thumb 1"),
(47,"Left Thumb 2"),
(48,"Left Thumb 3"),
(49,"Right Thumb 1"),
(50,"Right Thumb 2"),
(51,"Right Thumb 3"),
(52,"Left Toe"),
(53,"Right Toe"),
(54,"Neck 1"),
(55,"Neck 2"),
(56,"Right Finger 1"),
(57,"Right Claw 1"),
(58,"Right Finger 2"),
(59,"Right Claw 2"),
(60,"Right Finger 3"),
(61,"Right Claw 3"),
(62,"Left Finger 1"),
(63,"Left Claw 1"),
(64,"Left Finger 2"),
(65,"Left Claw 2"),
(66,"Left Finger 3"),
(67,"Left Claw 3"),
(68,"Right Toe 1"),
(69,"Right Toe 2"),
(70,"Left Toe 1"),
(71,"Left Toe 2"),
(72,"Tail 1"),
(73,"Tail 2"),
(74,"Tail 3"),
(75,"Tail 4"),
(76,"Left Up Arm"),
(77,"Right Up Arm"),
(78,"Left Wrist"),
(79,"Right Wrist"),
(80,"Lower Neck"),
(81,"Upper Neck"),
(82,"Left Leg"),
(83,"Right Leg"),
(84,"Left Ankle"),
(85,"Right Ankle"),
(86,"Waist"),
(87,"Left Ear 1"),
(88,"Right Ear 1"),
(89,"Left Ear 2"),
(90,"Right Ear 2"),
(91,"Left Ear 3"),
(92,"Right Ear 3"),
(93,"Tail Fins"),
(94,"Right Pect Fin"),
(95,"Left Pect Fin"),
(96,"Body 1"),
(97,"Body 2"),
(98,"Body 3"),
(99,"Body 4"),
(100,"Body 5"),
(101,"Left Eye"),
(102,"Right Eye"),
(103,"innerMatSphere"),
(104,"outerMatSphere"),
(105,"nullMatSphere")]
sparse_list = {}

for var in sparse_vars:
  sparse_list[var[0]] = var[1]

stringResourceList[1024] = sparse_list

## GetStringRes Values (English Version)
## Numeric
## 1028
sparse_vars=[(1,"Taper"),
(2,"Twist"),
(3,"Side-Side"),
(4,"Bend"),
(5,"Scale"),
(6,"xScale"),
(7,"yScale"),
(8,"zScale"),
(9,"xRotate"),
(10,"yRotate"),
(11,"zRotate"),
(12,"xTrans"),
(13,"yTrans"),
(14,"zTrans"),
(15,"Focal"),
(16,"Pitch"),
(17,"Yaw"),
(18,"Roll"),
(19,"Red"),
(20,"Green"),
(21,"Blue"),
(22,"Intensity"),
(23,"Turn"),
(24,"Front-Back"),
(25,"DollyX"),
(26,"DollyY"),
(27,"DollyZ"),
(28,"Shadow"),
(29,"Map Size"),
(30,"PanX"),
(31,"PanY"),
(32,"Zoom"),
(33,"xTranB"),
(34,"yTranB"),
(35,"zTranB"),
(36,"xOffset"),
(37,"yOffset"),
(38,"zOffset"),
(39,"xOrbit"),
(40,"yOrbit"),
(41,"zOrbit"),
(42,"Hand Type"),
(43,"BreastSize"),
(44,"OriginX"),
(45,"OriginY"),
(46,"OriginZ"),
(47,"Fatness"),
(48,"Grasp"),
(49,"Thumb Grasp"),
(50,"Spread"),
(51,"Curve"),
(52,"curve"),
(53,"Up-Down")]
sparse_list = {}

for var in sparse_vars:
  sparse_list[var[0]] = var[1]

stringResourceList[1028] = sparse_list

## GetStringRes Values (English Version)
## Numeric
## 1029
sparse_vars=[ (1,"No Bump"),
(2, "Runtime/Textures/Male Muscle Bump.bum"),
(3, "Runtime/Textures/Female Muscle Bump.bum"),
(4, "None"),
(5, "Runtime/Textures/Male Muscle Texture.tif"),
(6, "Runtime/Textures/Female Muscle Texture.tif"),
(7, "Runtime/Textures/Ground Default Texture.tif"),
(8, "Runtime/Textures/male casual texture.tif"),
(9, "Runtime/Textures/female casual texture.tif"),
(10,"Runtime/Textures/male nude texture.tif"),
(11,"Runtime/Textures/female nude texture.tif"),
(12,"Runtime/Textures/male business texture.tif"),
(13,"Runtime/Textures/female business texture.tif"),
(14,"Runtime/Textures/child nude texture.tif"),
(15,"Runtime/Textures/child casual texture.tif"),
(16,"Runtime/Textures/Ground Default Texture.bump"),
(17,"Runtime/Textures/Poser 3 Textures/AngelfishMap.tif"),
(18,"Runtime/Textures/Poser 3 Textures/Biz Man Texture.TIF"),
(19,"Runtime/Textures/Poser 3 Textures/Biz Woman Texture.TIF"),
(20,"Runtime/Textures/Poser 3 Textures/Casual Child Texture.TIF"),
(21,"Runtime/Textures/Poser 3 Textures/Casual Man Texture.TIF"),
(22,"Runtime/Textures/Poser 3 Textures/Casual Woman Texture.TIF"),
(23,"Runtime/Textures/Poser 3 Textures/Cat Texture.TIF"),
(24,"Runtime/Textures/Poser 3 Textures/Child Hair Texture.TIF"),
(25,"Runtime/Textures/Poser 3 Textures/Dog Texture.TIF"),
(26,"Runtime/Textures/Poser 3 Textures/Dolphin Texture.TIF"),
(27,"Runtime/Textures/Poser 3 Textures/Female Hair 1 Texture.TIF"),
(28,"Runtime/Textures/Poser 3 Textures/Female Hair 2 Texture.TIF"),
(29,"Runtime/Textures/Poser 3 Textures/Female Hair 3 Texture.TIF"),
(30,"Runtime/Textures/Poser 3 Textures/Female Hair 4 Texture.TIF"),
(31,"Runtime/Textures/Poser 3 Textures/Female Hair 5 Texture.TIF"),
(32,"Runtime/Textures/Poser 3 Textures/frogmap.tif"),
(33,"Runtime/Textures/Poser 3 Textures/Hand Texture.tif"),
(34,"Runtime/Textures/Poser 3 Textures/Horse Texture.TIF"),
(35,"Runtime/Textures/Poser 3 Textures/lionmap.tif"),
(36,"Runtime/Textures/Poser 3 Textures/Male Hair 1 Texture.TIF"),
(37,"Runtime/Textures/Poser 3 Textures/Male Hair 2 Texture.TIF"),
(38,"Runtime/Textures/Poser 3 Textures/Male Hair 3 Texture.TIF"),
(39,"Runtime/Textures/Poser 3 Textures/Male Hair 4 Texture.TIF"),
(40,"Runtime/Textures/Poser 3 Textures/Male Hair 5 Texture.TIF"),
(41,"Runtime/Textures/Poser 3 Textures/Nude Child Texture.TIF"),
(42,"Runtime/Textures/Poser 3 Textures/Nude Man Texture.TIF"),
(43,"Runtime/Textures/Poser 3 Textures/Nude Woman texture.TIF"),
(44,"Runtime/Textures/Poser 3 Textures/raptor texture.bum"),
(45,"Runtime/Textures/Poser 3 Textures/Raptor Texture.TIF"),
(46,"Runtime/Textures/Poser 3 Textures/wolfmap.tif"),
(47,"Runtime/Textures/Poser 4 Textures/P4 man bump.bum"),
(48,"Runtime/Textures/Poser 4 Textures/P4 man bump.TIF"),
(49,"Runtime/Textures/Poser 4 Textures/P4 man texture.TIF"),
(50,"Runtime/Textures/Poser 4 Textures/P4 man texture2.TIF"),
(51,"Runtime/Textures/Poser 4 Textures/P4 woman bump.bum"),
(52,"Runtime/Textures/Poser 4 Textures/P4 woman bump.TIF"),
(53,"Runtime/Textures/Poser 4 Textures/P4 woman texture.TIF"),
(54,"Runtime/Textures/Poser 4 Textures/P4 woman texture2.TIF"),
(55,"Runtime/Textures/Poser 4 Textures/P4casboy.tif"),
(56,"Runtime/Textures/Poser 4 Textures/P4casgirl.tif"),
(57,"Runtime/Textures/Poser 4 Textures/P4infant.tif"),
(58,"Runtime/Textures/Poser 4 Textures/P4NudBoy.tif"),
(59,"Runtime/Textures/Poser 4 Textures/P4NudGrl.tif"),
(60,"Runtime/Textures/Poser 4 Textures/snakelo.TIF")]
sparse_list = {}

for var in sparse_vars:
  sparse_list[var[0]] = var[1]

stringResourceList[1029] = sparse_list

## GetStringRes Values (English Version)
## Numeric
## 1052
sparse_vars=[
( 18, "Runtime/Geometries/maleOrig/maleOrig.obj"),
( 19, "Runtime/Geometries/maleNudeHi/maleNudeHi.obj"),
( 20, "Runtime/Geometries/maleNudeLo/maleNudeLo.obj"),
( 21, "Runtime/Geometries/maleSuitHi/maleSuitHi.obj"),
( 22, "Runtime/Geometries/maleSuitLo/maleSuitLo.obj"),
( 23, "Runtime/Geometries/maleCasHi/maleCasHi.obj"),
( 24, "Runtime/Geometries/maleCasLo/maleCasLo.obj"),
( 25, "Runtime/Geometries/maleSkeleton/maleSkeleton.obj"),
( 26, "Runtime/Geometries/maleStick/maleStick.obj"),
( 27, "Runtime/Geometries/femaleOrig/femaleOrig.obj"),
( 28, "Runtime/Geometries/femaleNudeHi/femaleNudeHi.obj"),
( 29, "Runtime/Geometries/femaleNudeLo/femaleNudeLo.obj"),
( 30, "Runtime/Geometries/femaleSuitHi/femaleSuitHi.obj"),
( 31, "Runtime/Geometries/femaleSuitLo/femaleSuitLo.obj"),
( 32, "Runtime/Geometries/femaleCasHi/femaleCasHi.obj"),
( 33, "Runtime/Geometries/femaleCasLo/femaleCasLo.obj"),
( 34, "Runtime/Geometries/femaleSkeleton/femaleSkeleton.obj"),
( 35, "Runtime/Geometries/femaleStick/femaleStick.obj"),
( 36, "Runtime/Geometries/childNudeHi/childNudeHi.obj"),
( 37, "Runtime/Geometries/childNudeLo/childNudeLo.obj"),
( 38, "Runtime/Geometries/childCasHi/childCasHi.obj"),
( 39, "Runtime/Geometries/childCasLo/childCasLo.obj"),
( 40, "Runtime/Geometries/childStick/childStick.obj")]
sparse_list = {}

for var in sparse_vars:
  sparse_list[var[0]] = var[1]

stringResourceList[1052] = sparse_list

# print(stringResourceList[1029][53])
